Repository ESP111111/Event-Planner-System, pull requests merged in 2024-03, with the labels that each got.

#1 project-base
  Event-Planner-System/pom.xml
  Event-Planner-System/src/main/java/newpackage/users.java
  Event-Planner-System/target/Event-Planner-System-1.0-SNAPSHOT.jar
  Event-Planner-System/target/classes/newpackage/users.class
  Event-Planner-System/target/maven-archiver/pom.properties
  Event-Planner-System/target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
  Event-Planner-System/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
  Event-Planner-System/target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/createdFiles.lst
  Event-Planner-System/target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst
Labels: enhancement, Rawand

#2 DB
  Event-Planner-System/eventplanner.sql
  Event-Planner-System/pom.xml
  Event-Planner-System/src/main/java/newpackage/DatabaseConnection.java
  Event-Planner-System/src/main/java/newpackage/main_test.java
  Event-Planner-System/src/main/java/newpackage/users.java
  Event-Planner-System/target/Event-Planner-System-1.0-SNAPSHOT.jar
  Event-Planner-System/target/classes/newpackage/DatabaseConnection.class
  Event-Planner-System/target/classes/newpackage/main_test.class
  Event-Planner-System/target/classes/newpackage/users.class
  Event-Planner-System/target/maven-archiver/pom.properties
  Event-Planner-System/target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
  Event-Planner-System/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
Labels: Rawand, devlopment

#3 signup
  Event-Planner-System/src/main/java/newpackage/DatabaseConnection.java
  Event-Planner-System/src/main/java/newpackage/main_test.java
  Event-Planner-System/src/main/java/newpackage/users.java
  Event-Planner-System/target/classes/newpackage/DatabaseConnection.class
  Event-Planner-System/target/classes/newpackage/main_test.class
  Event-Planner-System/target/classes/newpackage/users.class
Labels: Rawand, devlopment

#4 DB-last-update
  Event-Planner-System/eventplanner .sql
Labels: enhancement, Rawand, devlopment

#5 login
  Event-Planner-System/eventplanner.sql
  Event-Planner-System/src/main/java/newpackage/main_test.java
  Event-Planner-System/src/main/java/newpackage/users.java
  Event-Planner-System/target/classes/newpackage/main_test.class
  Event-Planner-System/target/classes/newpackage/users.class
Labels: Rawand, devlopment

#6 login-signup-profile(CMD)
  Event-Planner-System/src/main/java/newpackage/main_test.java
  Event-Planner-System/src/main/java/newpackage/users.java
  Event-Planner-System/target/classes/newpackage/main_test.class
  Event-Planner-System/target/classes/newpackage/users.class
Labels: Rawand, devlopment

#7 Insert new event
  Event-Planner-System/src/main/java/newpackage/Event.java
  Event-Planner-System/src/main/java/newpackage/Events.java
  Event-Planner-System/src/main/java/newpackage/main_test.java
  Event-Planner-System/src/main/java/newpackage/users.java
  Event-Planner-System/target/classes/newpackage/Event.class
  Event-Planner-System/target/classes/newpackage/Events.class
  Event-Planner-System/target/classes/newpackage/main_test.class
  Event-Planner-System/target/classes/newpackage/users.class
  Event-Planner-System/target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
  Event-Planner-System/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
Labels: Rawand, devlopment

#8 Events-show-one-event
  Event-Planner-System/src/main/java/newpackage/Events.java
  Event-Planner-System/src/main/java/newpackage/main_test.java
  Event-Planner-System/target/classes/newpackage/Events.class
  Event-Planner-System/target/classes/newpackage/main_test.class
Labels: Rawand, devlopment

#9 meta data (Images and Videos).
  Event-Planner-System/src/main/java/newpackage/Events.java
  Event-Planner-System/src/main/java/newpackage/main_test.java
  Event-Planner-System/target/classes/newpackage/Events.class
  Event-Planner-System/target/classes/newpackage/main_test.class
Labels: Rawand, devlopment

#10 Event invitations settings
  Event-Planner-System/src/main/java/newpackage/Events.java
  Event-Planner-System/src/main/java/newpackage/main_test.java
  Event-Planner-System/target/classes/newpackage/Events.class
  Event-Planner-System/target/classes/newpackage/main_test.class
Labels: Rawand, devlopment

#11 Delete event
  Event-Planner-System/src/main/java/newpackage/Events.java
  Event-Planner-System/src/main/java/newpackage/main_test.java
  Event-Planner-System/target/classes/newpackage/Events.class
  Event-Planner-System/target/classes/newpackage/main_test.class
Labels: Rawand, devlopment

#12 ZZ
  Event-Planner-System/src/main/java/newpackage/ZZ.java
  Event-Planner-System/src/main/java/newpackage/main_test.java
Labels: devlopment, Oday

#13 last
  Event-Planner-System/src/main/java/newpackage/ZZ.java
  Event-Planner-System/src/main/java/newpackage/main_test.java
Labels: enhancement, Rawand

#14 Places
  Event-Planner-System/eventplanner.sql
  Event-Planner-System/src/main/java/newpackage/Events.java
  Event-Planner-System/src/main/java/newpackage/main_test.java
  Event-Planner-System/src/main/java/newpackage/places.java
  Event-Planner-System/target/classes/newpackage/Events.class
  Event-Planner-System/target/classes/newpackage/main_test.class
  Event-Planner-System/target/classes/newpackage/places.class
  Event-Planner-System/target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
  Event-Planner-System/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
Labels: enhancement, devlopment, Aya

#15 place-events
  Event-Planner-System/src/main/java/newpackage/main_test.java
  Event-Planner-System/target/classes/newpackage/main_test.class
Labels: enhancement, Aya

#16 search
  Event-Planner-System/src/main/java/newpackage/main_test.java
  Event-Planner-System/src/main/java/newpackage/places.java
  Event-Planner-System/target/classes/newpackage/main_test.class
  Event-Planner-System/target/classes/newpackage/places.class
  Event-Planner-System/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
Labels: devlopment, Oday

#17 clean code
  Event-Planner-System/src/main/java/newpackage/main_test.java
  Event-Planner-System/target/classes/newpackage/main_test.class
  Event-Planner-System/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
Labels: enhancement, Aya

#18 Visitors
  Event-Planner-System/src/main/java/newpackage/Visitor.java
  Event-Planner-System/src/main/java/newpackage/main_test.java
  Event-Planner-System/target/classes/newpackage/Visitor.class
  Event-Planner-System/target/classes/newpackage/main_test.class
  Event-Planner-System/target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
  Event-Planner-System/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
Labels: Rawand, devlopment

#19 finance
  Event-Planner-System/FinanceReport.png
  Event-Planner-System/src/main/java/newpackage/finance.java
  Event-Planner-System/src/main/java/newpackage/main_test.java
  Event-Planner-System/target/Event-Planner-System-1.0-SNAPSHOT.jar
  Event-Planner-System/target/classes/newpackage/finance.class
  Event-Planner-System/target/classes/newpackage/main_test.class
  Event-Planner-System/target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
  Event-Planner-System/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
Labels: Rawand, devlopment

#20 Forecasting-report
  Event-Planner-System/FinanceReport.png
  Event-Planner-System/ForcastingReport.png
  Event-Planner-System/src/main/java/newpackage/finance.java
  Event-Planner-System/src/main/java/newpackage/main_test.java
  Event-Planner-System/target/classes/newpackage/finance.class
  Event-Planner-System/target/classes/newpackage/main_test.class
Labels: enhancement, devlopment, Aya

#21 EN
  Event-Planner-System/src/main/java/newpackage/EP.png
  Event-Planner-System/src/main/java/newpackage/NotificationService.java
  Event-Planner-System/src/main/java/newpackage/finance.java
  Event-Planner-System/src/main/java/newpackage/main_test.java
  Event-Planner-System/src/main/java/newpackage/users.java
  Event-Planner-System/target/classes/newpackage/NotificationService.class
  Event-Planner-System/target/classes/newpackage/finance.class
  Event-Planner-System/target/classes/newpackage/main_test.class
  Event-Planner-System/target/classes/newpackage/users.class
  Event-Planner-System/target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
  Event-Planner-System/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
Labels: enhancement, devlopment, Oday

#23 Change-files-location
  .classpath
  .gitignore
  .project
  .settings/org.eclipse.core.resources.prefs
  .settings/org.eclipse.jdt.core.prefs
  Event-Planner-System/target/Event-Planner-System-1.0-SNAPSHOT.jar
  Event-Planner-System/target/classes/newpackage/DatabaseConnection.class
  Event-Planner-System/target/classes/newpackage/Event.class
  Event-Planner-System/target/classes/newpackage/Events.class
  Event-Planner-System/target/classes/newpackage/NotificationService.class
  Event-Planner-System/target/classes/newpackage/Visitor.class
  Event-Planner-System/target/classes/newpackage/finance.class
  Event-Planner-System/target/classes/newpackage/main_test.class
  Event-Planner-System/target/classes/newpackage/places.class
  Event-Planner-System/target/classes/newpackage/users.class
  Event-Planner-System/target/maven-archiver/pom.properties
  Event-Planner-System/target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
  Event-Planner-System/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
  Event-Planner-System/target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/createdFiles.lst
  Event-Planner-System/target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst
  FinanceReport.png
  ForcastingReport.png
  bin/.gitignore
  bin/.project
  bin/.settings/org.eclipse.core.resources.prefs
  bin/FinanceReport.png
  bin/ForcastingReport.png
  bin/eventplanner.sql
  bin/pom.xml
  bin/src/main/java/newpackage/DatabaseConnection.class
  bin/src/main/java/newpackage/EP.png
  bin/src/main/java/newpackage/Event.class
  bin/src/main/java/newpackage/Events.class
  bin/src/main/java/newpackage/NotificationService.class
  bin/src/main/java/newpackage/Visitor.class
  bin/src/main/java/newpackage/finance.class
  bin/src/main/java/newpackage/main_test.class
  bin/src/main/java/newpackage/places.class
  bin/src/main/java/newpackage/users.class
  bin/src/test/resources/features/Login.feature
  bin/src/test/resources/features/LoginTest.class
  bin/src/test/resources/features/TestRunner.class
  eventplanner.sql
  features/Login.feature
  features/Signup.feature
  features/UpdateUser.feature
  pom.xml
  src/main/java/newpackage/DatabaseConnection.java
  src/main/java/newpackage/EP.png
  src/main/java/newpackage/Event.java
  src/main/java/newpackage/Events.java
  src/main/java/newpackage/NotificationService.java
  src/main/java/newpackage/Visitor.java
  src/main/java/newpackage/finance.java
  src/main/java/newpackage/main_test.java
  src/main/java/newpackage/places.java
  src/main/java/newpackage/users.java
  src/test/java/CucumberTestRunner.java
  src/test/java/Test.java
Labels: enhancement, Rawand

#24 Sonar
  eventplanner.sql
  pom.xml
Labels: enhancement, Rawand

#25 Delete
  .github/workflows/main.yml
Labels: Rawand

#28 Update signup
  src/main/java/newpackage/users.java
Labels: Rawand

#29 Update login
  src/main/java/newpackage/users.java
Labels: Rawand

#32 Update users.java
  src/main/java/newpackage/users.java
Labels: Rawand

#33 Sonar
  FinanceReport.png
  ForcastingReport.png
  src/main/java/newpackage/DatabaseConnection.java
  src/main/java/newpackage/main_test.java
  src/main/java/newpackage/users.java
  src/main/resources/db.properties
Labels: enhancement, Rawand

#34 place-finance
  FinanceReport.png
  ForcastingReport.png
  features/enhancment finance report.feature
  features/finance report.feature
  features/insert_new_place.feature
  features/print_all_places.feature
  features/print_one_place.feature
  features/srch_bylocation.feature
  features/srch_byname.feature
  features/srch_byperiod.feature
  features/srch_byprice.feature
  src/main/java/newpackage/main_test.java
  src/main/java/newpackage/places.java
  src/test/java/Test.java
Labels: enhancement, Rawand, Oday, Aya

#35 test
  FinanceReport.png
  ForcastingReport.png
  features/add_Invitation.feature
  features/add_meta.feature
  features/get_Invitations.feature
  features/get_event_meta.feature
  features/get_one_event.feature
  features/insert_new_event.feature
  features/my_invitations.feature
  features/order_to_place.feature
  features/print_categories.feature
  features/print_org_events.feature
  src/main/java/newpackage/Events.java
  src/main/java/newpackage/Visitor.java
  src/main/java/newpackage/main_test.java
  src/test/java/Test.java
Labels: enhancement, Rawand, Oday, Aya

#37 Code
  src/main/java/newpackage/SimpleFormatter.java
  src/main/java/newpackage/main_test.java
Labels: enhancement, Rawand, Oday, Aya

#38 xml
  pom.xml
Labels: Rawand

#39 AA
  pom.xml
Labels: Aya

#40 BB
  pom.xml
Labels: documentation, Aya
